$envFile = Join-Path $PSScriptRoot ".env"
$outFile = Join-Path $PSScriptRoot "js\config.js"

if (-not (Test-Path $envFile)) {
    Write-Error 'Missing .env file. Create one and add PAYSTACK_PUBLIC_KEY=your_key'
    exit 1
}

$key = $null
foreach ($line in Get-Content $envFile) {
    $trimmed = $line.Trim()
    if ($trimmed -and -not $trimmed.StartsWith("#") -and $trimmed.StartsWith("PAYSTACK_PUBLIC_KEY=")) {
        $key = $trimmed.Substring("PAYSTACK_PUBLIC_KEY=".Length).Trim()
        break
    }
}

if (-not $key) {
    Write-Error 'PAYSTACK_PUBLIC_KEY not found in .env'
    exit 1
}

$output = "/* Generated by build-config.ps1 - do not edit. Run `"powershell -File build-config.ps1`" to regenerate. */`nwindow.PAYSTACK_PUBLIC_KEY = " + (ConvertTo-Json $key) + ";`n"
Set-Content -Path $outFile -Value $output -Encoding ASCII
Write-Host "Generated $outFile"